src/WebApp/Movies.Client.Hybrid/Controllers/AccountController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Movies.Client.Hybrid.Controllers
{
	[Authorize]
	public class AccountController : Controller
	{
		public IActionResult AccessDenied()
		{
			return View();
		}
	}
}

src/WebApp/Movies.Client.Hybrid/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Movies.Client.Hybrid.Controllers
{
	public class HomeController : Controller
	{
		public IActionResult Index()
		{
			return View();
		}
	}
}

src/WebApp/Movies.Client.Hybrid/Controllers/IdentityController.cs
using IdentityModel.Client;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication.OpenIdConnect;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using Microsoft.IdentityModel.Protocols.OpenIdConnect;
using System.Diagnostics;

namespace Movies.Client.Hybrid.Controllers
{
	[Authorize]
	public class IdentityController : Controller
	{
		private readonly IHttpClientFactory _httpClientFactory;
		public IdentityController(IHttpClientFactory httpClientFactory)
		{
			_httpClientFactory = httpClientFactory;
		}

		[AllowAnonymous]
		public IActionResult Login()
		{
			// A ChallengeResult is an ActionResult that when executed, challenges the given authentication schemes' handler
			// A challenge is basically a way of saying "I don't know who this user is, please verify their identity".
			// So if the authentication handler triggered is e.g. the Facebook authentication handler,
			// it will react to the challenge by issuing a redirect to the Facebook authentication page.
			// A local account authentication handler might issue a redirect to the local sign-in page.

			// In the case of JWT Bearer authentication, the handler cannot do anything other than respond with a 401 status code and leave it up to the caller to authenticate themselves properly.
			// var challenge = Challenge(new AuthenticationProperties

			return Challenge(new AuthenticationProperties
			{
				RedirectUri = "/"
			});
		}

		public async Task Logout()
		{
			// Signout from the browser
			await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);

			// Signout from the OIDC
			await HttpContext.SignOutAsync(OpenIdConnectDefaults.AuthenticationScheme);
		}

		public async Task<ActionResult> UserInfo()
		{
			if (User.Identity.IsAuthenticated == false)
			{
				return Forbid();
			}

			var client = _httpClientFactory.CreateClient("IDClient");
			var discoveryDocumentResponse = await client.GetDiscoveryDocumentAsync();
			if (discoveryDocumentResponse.IsError)
			{
				return null;
			}

			var userInfo = await client.GetUserInfoAsync(new UserInfoRequest()
			{
				Address = discoveryDocumentResponse.UserInfoEndpoint,
				Token = await HttpContext.GetTokenAsync(OpenIdConnectParameterNames.AccessToken)
			});

			await LogTokensAndClaims();

			return View(userInfo);
		}

		public async Task LogTokensAndClaims()
		{
			var identityToken = await HttpContext.GetTokenAsync(OpenIdConnectParameterNames.IdToken);

			Debug.WriteLine($"Identity token: {identityToken}");

			var accessToken = await HttpContext.GetTokenAsync(OpenIdConnectParameterNames.AccessToken);

			Debug.WriteLine($"Access token: {accessToken}");

			foreach (var claim in User.Claims)
			{
				Debug.WriteLine($"Claim type: {claim.Type} - Claim value: {claim.Value}");
			}

			// cookies decryption (for testing)

			// ONE - grab the CookieAuthenticationOptions instance
			var cookieAuthenticationOptions = HttpContext.RequestServices
				.GetRequiredService<IOptionsMonitor<CookieAuthenticationOptions>>()
				.Get(CookieAuthenticationDefaults.AuthenticationScheme); //or use .Get("Cookies")

			// TWO - Get the encrypted cookie value
			var cookie = cookieAuthenticationOptions.CookieManager
				.GetRequestCookie(HttpContext, cookieAuthenticationOptions.Cookie.Name);

			// THREE - decrypt it
			var unprotectedCookie = cookieAuthenticationOptions.TicketDataFormat.Unprotect(cookie);
		}
	}
}

src/WebApp/Movies.Client.Hybrid/Controllers/MoviesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OpenAPIConsumer;

namespace Movies.Client.Hybrid.Controllers
{
	[Authorize]
	public class MoviesController : Controller
	{
		private readonly MoviesAPIClient _client;

		public MoviesController(MoviesAPIClient client)
		{
			_client = client;
		}

		[Authorize(Roles = "admin")]
		public IActionResult OnlyAdmin()
		{
			return Content("Admin page");
		}

		// GET: Movies
		public async Task<IActionResult> Index()
		{
			var movies = await _client.GetMoviesAsync();

			return View(movies);
		}

		// GET: Movies/Details/5
		public async Task<IActionResult> Details(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var movie = await _client.GetMovieAsync(id.Value);

			if (movie == null)
			{
				return NotFound();
			}

			return View(movie);
		}

		// GET: Movies/Create
		public IActionResult Create()
		{
			return View();
		}

		// POST: Movies/Create
		// To protect from overposting attacks, enable the specific properties you want to bind to.
		// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create([Bind("Id,Title,Genre,Rating,ReleaseDate,ImageUrl,Owner")] Movie movie)
		{
			if (ModelState.IsValid)
			{
				await _client.PostMovieAsync(movie);

				return RedirectToAction(nameof(Index));
			}

			return View(movie);
		}

		// GET: Movies/Edit/5
		public async Task<IActionResult> Edit(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var movie = await _client.GetMovieAsync(id.Value);

			if (movie == null)
			{
				return NotFound();
			}

			return View(movie);
		}

		// POST: Movies/Edit/5
		// To protect from overposting attacks, enable the specific properties you want to bind to.
		// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Genre,Rating,ReleaseDate,ImageUrl,Owner")] Movie movie)
		{
			if (id != movie.Id)
			{
				return NotFound();
			}

			if (ModelState.IsValid)
			{
				await _client.PutMovieAsync(id, movie);

				return RedirectToAction(nameof(Index));
			}
			return View(movie);
		}

		// GET: Movies/Delete/5
		public async Task<IActionResult> Delete(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var movie = await _client.GetMovieAsync(id.Value);

			if (movie == null)
			{
				return NotFound();
			}

			return View(movie);
		}

		// POST: Movies/Delete/5
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> DeleteConfirmed(int id)
		{
			await _client.DeleteMovieAsync(id);

			return RedirectToAction(nameof(Index));
		}
	}
}

src/WebApp/Movies.Client.Hybrid/Views/Home/Index.cshtml
<h1 style="text-align:center">
	Home Page (Hybrid)
</h1>

src/WebApp/Movies.Client.Hybrid/Views/Movies/Create.cshtml
@model OpenAPIConsumer.Movie

@{
	ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Movie</h4>
<hr />
<div class="row">
	<div class="col-md-4">
		<form asp-action="Create">
			<div asp-validation-summary="ModelOnly" class="text-danger"></div>
			<div class="form-group">
				<label asp-for="Title" class="control-label"></label>
				<input asp-for="Title" class="form-control" />
				<span asp-validation-for="Title" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Genre" class="control-label"></label>
				<input asp-for="Genre" class="form-control" />
				<span asp-validation-for="Genre" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Rating" class="control-label"></label>
				<input asp-for="Rating" class="form-control" />
				<span asp-validation-for="Rating" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="ReleaseDate" class="control-label"></label>
				<input asp-for="ReleaseDate" class="form-control" />
				<span asp-validation-for="ReleaseDate" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="ImageUrl" class="control-label"></label>
				<input asp-for="ImageUrl" class="form-control" />
				<span asp-validation-for="ImageUrl" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Owner" class="control-label"></label>
				<input asp-for="Owner" class="form-control" />
				<span asp-validation-for="Owner" class="text-danger"></span>
			</div>
			<div class="form-group" style="margin-top:5px;">
				<input type="submit" value="Create" class="btn btn-primary" />
			</div>
		</form>
	</div>
</div>

<div>
	<a asp-action="Index">Back to List</a>
</div>

@section Scripts {
	@{
		await Html.RenderPartialAsync("_ValidationScriptsPartial");
	}
}

src/WebApp/Movies.Client.Hybrid/Views/Movies/Delete.cshtml
@model OpenAPIConsumer.Movie

@{
	ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
	<h4>Movie</h4>
	<hr />
	<dl class="row">
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.Title)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.Title)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.Genre)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.Genre)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.Rating)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.Rating)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.ReleaseDate)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.ReleaseDate)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.ImageUrl)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.ImageUrl)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.Owner)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.Owner)
		</dd>
	</dl>

	<form asp-action="Delete">
		<input type="hidden" asp-for="Id" />
		<input type="submit" value="Delete" class="btn btn-danger" /> |
		<a asp-action="Index">Back to List</a>
	</form>
</div>

src/WebApp/Movies.Client.Hybrid/Views/Movies/Details.cshtml
@model OpenAPIConsumer.Movie

@{
	ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
	<h4>Movie</h4>
	<hr />
	<dl class="row">
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.Title)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.Title)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.Genre)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.Genre)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.Rating)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.Rating)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.ReleaseDate)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.ReleaseDate)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.ImageUrl)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.ImageUrl)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.Owner)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.Owner)
		</dd>
	</dl>
</div>
<div>
	<a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
	<a asp-action="Index">Back to List</a>
</div>

src/WebApp/Movies.Client.Hybrid/Views/Movies/Edit.cshtml
@model OpenAPIConsumer.Movie

@{
	ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Movie</h4>
<hr />
<div class="row">
	<div class="col-md-4">
		<form asp-action="Edit">
			<div asp-validation-summary="ModelOnly" class="text-danger"></div>
			<input type="hidden" asp-for="Id" />
			<div class="form-group">
				<label asp-for="Title" class="control-label"></label>
				<input asp-for="Title" class="form-control" />
				<span asp-validation-for="Title" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Genre" class="control-label"></label>
				<input asp-for="Genre" class="form-control" />
				<span asp-validation-for="Genre" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Rating" class="control-label"></label>
				<input asp-for="Rating" class="form-control" />
				<span asp-validation-for="Rating" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="ReleaseDate" class="control-label"></label>
				<input asp-for="ReleaseDate" class="form-control" />
				<span asp-validation-for="ReleaseDate" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="ImageUrl" class="control-label"></label>
				<input asp-for="ImageUrl" class="form-control" />
				<span asp-validation-for="ImageUrl" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Owner" class="control-label"></label>
				<input asp-for="Owner" class="form-control" />
				<span asp-validation-for="Owner" class="text-danger"></span>
			</div>
			<div class="form-group" style="margin-top:5px;">
				<input type="submit" value="Save" class="btn btn-primary" />
			</div>
		</form>
	</div>
</div>

<div>
	<a asp-action="Index">Back to List</a>
</div>

@section Scripts {
	@{
		await Html.RenderPartialAsync("_ValidationScriptsPartial");
	}
}

src/WebApp/Movies.Client.Hybrid/Views/Movies/Index.cshtml
@model IEnumerable<OpenAPIConsumer.Movie>

@{
	ViewData["Title"] = "Index";
}

<p>
	<a asp-action="Create">Create New</a>
</p>
<table class="table">
	<thead>
		<tr>
			<th>
				@Html.DisplayNameFor(model => model.Title)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Genre)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Rating)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.ReleaseDate)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.ImageUrl)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Owner)
			</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		@foreach (var item in Model)
		{
			<tr>
				<td>
					@Html.DisplayFor(modelItem => item.Title)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Genre)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Rating)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.ReleaseDate)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.ImageUrl)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Owner)
				</td>
				<td>
					<a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
					<a asp-action="Details" asp-route-id="@item.Id">Details</a> |
					<a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
				</td>
			</tr>
		}
	</tbody>
</table>

src/WebApp/Movies.Client.Hybrid/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - Movies.Client.Hybrid</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/Movies.Client.styles.css" asp-append-version="true" />
</head>
<body>
	<div class="container">
		<nav class="navbar navbar-expand-lg navbar-light bg-light">
			<a class="nav-link" href="/">Home</a>
			<a class="nav-link" asp-controller="Movies" asp-action="Index">Movies</a>
			<div class="collapse navbar-collapse" id="navbarSupportedContent">
				@if (User.Identity.IsAuthenticated)
				{
					<ul class="navbar-nav mr-auto">
						<li class="nav-item active">
							<a class="nav-link" asp-controller="Identity" asp-action="UserInfo">User: @User.Identity.Name</a>
						</li>

						@if (User.IsInRole("admin"))
						{
							<li class="nav-item active">
								<a class="nav-link" asp-controller="Movies" asp-action="OnlyAdmin">Admin</a>
							</li>
						}

						<li class="nav-item active">
							<a class="nav-link" asp-controller="Identity" asp-action="Logout">Logout</a>
						</li>
					</ul>
				}
				else
				{
					<ul class="navbar-nav mr-auto">
						<li class="nav-item active">
							<a class="nav-link" asp-controller="Identity" asp-action="Login">Login</a>
						</li>
					</ul>
				}
			</div>
		</nav>
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>

	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>